Fix Android build not working due to too high JVM toolchain in common
Build was failing with:
```
Error: com.android.tools.r8.internal.nc: Sealed classes are not supported as program classes
```

Sealed classes were causing a byte code version that was too high.